name: growza
description: "AI-powered career advisor application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

#           
# Dependencies
#           
dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^14.0.0

  # Supabase (Backend)
  supabase_flutter: ^2.5.0

  # HTTP Requests
  dio: ^5.4.0

  # Local Storage
  shared_preferences: ^2.2.2

  # UI
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^6.0.0
  pinput: ^6.0.1
  flutter_svg: ^2.2.3
  app_links: ^6.3.2
  cached_network_image: ^3.3.0
  flutter_widget_from_html: ^0.16.0
  webview_flutter: ^4.8.0

  # File picking (for CV upload)
  file_picker: ^10.3.10
  dotted_border: ^2.1.0
  image_picker: ^1.0.4

  # State Management (optional)
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0

  # PDF Export
  pdf: ^3.11.1
  printing: ^5.13.4

  # Preview Capture Export
  screenshot: ^3.0.0

  # Utils
  url_launcher: ^6.2.4
  path_provider: ^2.1.1             
  permission_handler: ^11.3.1       
  intl: ^0.18.1
  http_parser: ^4.0.2
  just_audio: ^0.9.39
  camera: ^0.10.5+9
  record: ^6.1.1 
  video_compress: ^3.1.2

#           
# Dev Dependencies
#           
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # App Launcher Icon Generator
  flutter_launcher_icons: ^0.13.1

# Launcher Icons Config
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/branding/logo.png"
  min_sdk_android: 21

#           
# Flutter Configuration
#           
flutter:
  uses-material-design: true

  #           
  # Assets
  #           
  assets:
    - .env

    # Your auth images
    - assets/images/logo.png
    - assets/images/top_curve.png
    - assets/images/Bottom_curve.png
    - assets/images/forgot_password.png
    - assets/images/reset_password.png
    - assets/images/new_password.png
    - assets/images/success_illustration.png
    - assets/images/empty_resume.png
    - assets/images/home_light.png
    - assets/images/home_dark.png

    # Branding & Onboarding
    - assets/images/branding/
    - assets/images/onboarding/

    # Mock interview icons 
    - assets/images/mock_interview/
    # Feature assets
    - assets/images/career_build/
    - assets/images/ai_protifilo/
    - assets/images/market_insights/
    # Home icons
    - assets/images/home_icons/

    # Alerts icons folder
    - assets/images/alerts/

    # Your icons
    - assets/icons/

  #           
  # Fonts
  #           
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700